### ISSUE TITLE
Install documentation incorrect

### ISSUE THREAD

**Issue by nubelcr** [Tom-Hirschberger/MMM-SynologySurveillance#1]
I imagine anybody sort of familiar with MM would catch this but just wanted to give ya a heads up
cd ~/MagicMirror/modules
git clone https://github.com/Tom-Hirschberger/MMM-SynologySurveillance.git
**cd MMM-MplayerRadio** <<--- change to MMM-SynologySurveillance
npm install

**Comment by Tom-Hirschberger** [comment]
Hi, your absolute right.
Changed it a view seconds before.
Damn copy&paste mistake
