### ISSUE TITLE
How to add cams

### ISSUE THREAD

**Issue by kourkoulos** [Tom-Hirschberger/MMM-SynologySurveillance#15]
Hello,

how to you add more cameras in the code (for example Cam2):
------------------------------------------------------------------------------------
cams: [
							{
								alias: "Cam1",
								name: "NAME_IN_DS",
							}
						]
------------------------------------------------------------------------------------
How should the code look like for 2 or more camera?
Thanx.

**Comment by Tom-Hirschberger** [comment]
Hi,

if both cams are connected to the same diskstation simply add a second object to the cams array:

```json
cams: [
{
alias: "Cam1",
name: "NAME_IN_DS",
}, 
{
alias: "Cam2",
name: "NAME_OF_SECOND_Cam_IN_DS",
}
]
```

**Comment by kourkoulos** [comment]
Thank you! It workes perfect!

![MagicMirror](https://user-images.githubusercontent.com/112762467/206295969-83135ee1-4c03-4ad2-82e5-5a4964ba45a6.jpg)

**Comment by Tom-Hirschberger** [comment]
Great to see one more user that is happy
