### ISSUE TITLE
Insufficient user privilege after updates.

### ISSUE THREAD

**Issue by Gorkrul** [Tom-Hirschberger/MMM-SynologySurveillance#29]
Hi,
did some updates today - but now it seems to have a new issue (after working fine for some week)

DSM 7.2.2-72806
Surveilliance Station: 9.2.1-11380
Some more info: [out.txt](https://github.com/user-attachments/files/17610133/out.txt)
Error: ![error](https://github.com/user-attachments/assets/99f9c9c3-edfc-4c8b-983f-6c20590f18db)

i even switched the USER from MANAGER to ADMINISTRATOR (for testing) but same error (see picture)

kr

**Comment by Tom-Hirschberger** [comment]
Hi,

i updated my DS420+ to the same version as you after i finished the last changes.
Even my SurveillanceStation has the same version as yours.

My setup works well. A quick https check worked, too.

The question is where your setup differs of mine.

Do you have the "Surveillance Video Extension" installed?
My user is in the "users" group only.
It has rights to read/write "surveillance".
It has rights to access the apps "DSM" and "Surveillance Station".
In the Surveillance Station the user is "Manager of all Objects".

**Comment by Gorkrul** [comment]
It works again,
thy for sharing your Full-User-Settings!

My user is in the "users" group only.    (SAME)
It has rights to read/write "surveillance".    (CHANGED to R/W - before just READ)
It has rights to access the apps "DSM" and "Surveillance Station". (CHANGED to DSM, too. -before just SS)
In the Surveillance Station the user is "Manager of all Objects". (SAME)

thy

**Comment by Tom-Hirschberger** [comment]
Great to hear it working again.

If I have time I write a whole Readme part about the user setup
